version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ruc
    image: duc/ruc
    ports:
      - 5005:5005
    expose:
      - 5005
    volumes:
      - ./:/app
 